### PR TITLE
UXUI 222 - Adjust Sizes of components

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do?
- Stops the need for flag prefixed components
- This ties in with creating different buttons sizes
- Is just adds a few new classes to the component

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Check the code looks sane and follow the manual testing steps below

#### How should this be manually tested?
One you have checked out the branch
`npm install`
`npm run build-dev`
and open `dev/index.html` to view the component

#### Any background context you want to provide?
The Jira here is for buttons and not flags but they tie in A LOT

#### What are the relevant tickets?
https://holidayextras.jira.com/browse/UXUI-222

#### What gif best describes how you feel about this work?
size

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [ ] I agree with the assumptions made in the quality checklist.
- [ ] I’ve witnessed the work behaving as expected.
- [ ] I’ve run all the tests locally and they pass.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve checked for coding anti-patterns.
- [ ] I've checked this work against the requirements of the Jira.
- [ ] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by michaelcarter** [comment]
Shotgun SE/Guru

**Comment by hxgeorge** [comment]
Taking IP

**Comment by hxgeorge** [comment]
+1

**Comment by jodiedoubleday** [comment]
Just to point out this Jira really doesn't change that much visually. but its more noticeable in the docs - https://github.com/holidayextras/ui-toolkit/pull/7

**Comment by michaelcarter** [comment]
+1

**Comment by jodiedoubleday** [comment]
Closing due to https://github.com/holidayextras/ui-toolkit/pull/8

**Pull request closed without merging**
